# Modified from https://github.com/pmeier/light-the-torch
name: setup-dev-env
description: "Setup development environment"

inputs:
  python-version:
    default: "3.7"

runs:
  using: composite

  steps:
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Get pip cache path
      id: get-cache-path
      shell: bash
      run: |
        pip install appdirs
        CACHE_PATH=`python -c "import appdirs; print(appdirs.user_cache_dir('pip', appauthor=False))"`
        echo "::set-output name=path::$CACHE_PATH"

    - name: Restore pip cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.get-cache-path.outputs.path }}
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements-dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Upgrade or install system packages
      shell: bash
      run: python -m pip install --upgrade pip wheel

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install development requirements and project
      shell: bash
      run: |
        pip install doit
        pip install --pre light-the-torch